id: AC2CC91D8
title: Prayer for the Long Life of Chökyi Nyima Rinpoche
type: translation
pechas:
- I7EA42917
- I26108254
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:34:37.380279
  last_modified_at: 2023-01-04 11:34:37.380297
  collections:
  - Chökyi Nyima Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  I7EA42917/325B: 0EA8
  I26108254/5885: 0EA8
